### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by darkdarcool** [Highland-OS/Highland-OS#1]
What is this repo? What language is it in?

**Comment by IronCodem** [comment]
As you may have noticed I am making an OS. This is like a hub for all repos and for new people who want to join (adding a COC soon)

**Comment by IronCodem** [comment]
Added :)

**Comment by darkdarcool** [comment]
Oooo ok! What are language is the os in tho?

**Comment by jsavari** [comment]
I'm making a console os in java. Hey @Tr1angular, do you want to like combine our project into one os?
