### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jsavari** [Highland-OS/Highland-OS#2]
What language is this OS supposed to be in and is it GUI or Console. Also, what language. FYI I'm planning on contributing.

**Comment by iop3** [comment]
lol how do you expect Tr1angular to reply if you closed the issue.

**Comment by jsavari** [comment]
lmao, I didn't expect Yashas to answer.

**Comment by jsavari** [comment]
I already asked him before.

**Comment by iop3** [comment]
oh

**Comment by jsavari** [comment]
lmao

**Comment by IronCodem** [comment]
@X-Developer-Studios I didn't see this sorry.
Yeah you can join I'll invite

**Comment by Isaiah-Day** [comment]
hey, i'm repeating the question @X-Developer-Studios  asked: gui or console and what language? @Tr1angular

**Comment by IronCodem** [comment]
Both and any language that makes (the langs already used are preferred though)
