### ISSUE TITLE
you nasty hacker

### ISSUE THREAD

**Issue by firefish111** [Highland-OS/Highland-OS#3]
stop it you hacker please stop

**Comment by darkdarcool** [comment]
Why are you so mad that he committed to your repo, if you didn’t want him there, just ask us, don’t be a rude person about it

**Comment by firefish111** [comment]
I did ask but no-one responded

**Comment by darkdarcool** [comment]
Oh, ok, lemme see what I can do

**Comment by darkdarcool** [comment]
What did he commit to? And can I have link please? And is it in the org?

**Comment by firefish111** [comment]
Just pick a random repo in the org, on most of them either ask of the commits are falsely authored by him or he had committed and erased all history.

**Comment by darkdarcool** [comment]
If you out your gone finish fishin repo back in the org, I think that I can make him read only if it’s just him you don’t wanna committing

**Comment by firefish111** [comment]
that's how it was, only in the non web node team which I had created, where only I was a member. Add I said, this guy is a hacker, he can avoid read only

**Comment by darkdarcool** [comment]
He probably didn't hack, he probably just had perms to do so. If this is a big issue, take it up with the GitHub team, though I would just make sure there want something you did wrong.

**Comment by firefish111** [comment]
@darkdarcool If he isn't hacking, explain this
![image](https://user-images.githubusercontent.com/33234914/123869408-d9bea000-d928-11eb-9f91-3f5024da3756.png)

**Comment by darkdarcool** [comment]
I think that whippingdot or someone else in the org added him to it manually

**Comment by firefish111** [comment]
But it's the org? I checked and he had admin privileges. This sounds stupid cause i deleted the evidence (i.e. i deleted his admin perms), but he really did get an account that's impossible to login to, to add him to repo. this is too suspicious

**Comment by darkdarcool** [comment]
I don’t really think he that, maybe we left admin perms on him, but this isn’t a banable offense if he was just given the perms and used them thinking everyone has them. And he didn’t abuse them, he just tidied up your repo, so I think you should add him back, but make sure you give him member perms

**Comment by darkdarcool** [comment]
I my seems I can’t because he’s in the org, maybe add him shaping to the org, but give him read only privileges until his services are needed

**Comment by firefish111** [comment]
"tidied up" well, I said the changes he made were insignificant, but in the repl it weekly repo he changed  `var(--no)` to `$--no`, which doesn't work on scss apparently. Please can @Tr1angular not be a hacking nuisance.

**Comment by iop3** [comment]
i didn't understand 1 out of 3 words you guys have said. part of the reason why: i only have been on github for 3 months, I DONT EVEN KNOW HOW TO USE GIT (versioning control or smth like that?)! which is the whole point of github i think. xD

**Comment by firefish111** [comment]
he closed it, that fricking idiot

**Comment by firefish111** [comment]
tell us why you committed, if you wish to keep the issue closed. Either explain, or reopen the issue.

**Comment by Isaiah-Day** [comment]
I think you are being a bit to harsh accusing him of all that. Try to see how it could be a mistake. If you can't, bring it up with wippingdot as he is the head of the org (i think). @firefish111 
@Tr1angular : Can you respond with your point of view?

**Comment by firefish111** [comment]
> I think you are being a bit to harsh accusing him of all that. Try to see how it could be a mistake. If you can't, bring it up with wippingdot as he is the head of the org (i think). @firefish111
> @Tr1angular : Can you respond with your point of view?

achongos
